name: Docker Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build a docker container 
      run: docker build . -t node
      
    - name: Run the container
      run: docker run -p -d 3000:3000 --name runningnode node
