name: Docker Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build a docker image 
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/apprenticeship

    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_USER }}/apprenticeship
      
    - name: Run the container
      run: docker run -d -p 80:80 --name app ${{ secrets.DOCKER_USER }}/apprenticeship

    - name: Run tests
      uses: liatrio/github-actions/apprentice-action@master


    